spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
      url: jdbc:mysql://localhost:3307/shop
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      show-sql: false  # Hiển thị SQL trong logs (đã sửa từ "fasle" -> "true")
      hibernate:
        ddl-auto: none  # Các giá trị hợp lệ: none, update, create, create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect  # Đối với MySQL 8+
  sendgrid:
    api-key: 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
    fromEmail: lhhuy2005@gmail.com
    templateID: d-5922cc58601a480db52dc873a2f12965
    verificationLink: http://localhost:8080/user/confirm-email
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0
jwt:
  secretKey: abc@123
  expiryMinutes: 5
  expiryDay: 14
  accessKey: vx62zWtPZN5+yoQSSGU7d599Td1+2bu7XESjYv3JmIY=
  refreshKey: QftbDhd03kStt7H/G1COq8TfhRXHZtRtE2at3sFS97M=

